//
//  ViewBooks.h
//  Conquas
//
//  Created by Aparna Reddy Challa on 29/08/12.
//  Copyright (c) 2012 MobTwo Pte Ltd. All rights reserved.
//

#import <UIKit/UIKit.h>

@interface ViewBooks : UIViewController
{
    IBOutlet UIScrollView *viewScrollBooks;
}

@property (nonatomic, retain) UIScrollView *viewScrollBooks;

-(IBAction)btnBookCeramicTiling_1:(id)sender;
-(IBAction)btnBookCeramicTiling_2:(id)sender;
-(IBAction)btnBookCeramicTiling_3:(id)sender;
-(IBAction)btnBookCeramicTiling_4:(id)sender;
-(IBAction)btnBookCeramicTiling_5:(id)sender;
-(IBAction)btnBookCeramicTiling_6:(id)sender;
-(IBAction)btnBookCeramicTiling_7:(id)sender;
-(IBAction)btnBookCeramicTiling_8:(id)sender;
-(IBAction)btnBookCeramicTiling_9:(id)sender;
-(IBAction)btnBookCeramicTiling_10:(id)sender;
-(IBAction)btnBookCeramicTiling_11:(id)sender;
-(IBAction)btnBookCeramicTiling_12:(id)sender;
-(IBAction)btnBookMarbleAndGraniteFinishes_1:(id)sender;
-(IBAction)btnBookMarbleAndGraniteFinishes_2:(id)sender;
-(IBAction)btnBookMarbleAndGraniteFinishes_3:(id)sender;
-(IBAction)btnBookMarbleAndGraniteFinishes_4:(id)sender;
-(IBAction)btnBookMarbleAndGraniteFinishes_5:(id)sender;
-(IBAction)btnBookMarbleAndGraniteFinishes_6:(id)sender;
-(IBAction)btnBookMarbleAndGraniteFinishes_7:(id)sender;
-(IBAction)btnBookMarbleAndGraniteFinishes_8:(id)sender;
-(IBAction)btnBookMarbleAndGraniteFinishes_9:(id)sender;
-(IBAction)btnBookMarbleAndGraniteFinishes_10:(id)sender;
-(IBAction)btnBookMarbleAndGraniteFinishes_11:(id)sender;
-(IBAction)btnBookMarbleAndGraniteFinishes_12:(id)sender;
-(IBAction)btnBookMarbleAndGraniteFinishes_13:(id)sender;
-(IBAction)btnBookWaterproofingForInternalWetAreas_1:(id)sender;
-(IBAction)btnBookWaterproofingForInternalWetAreas_2:(id)sender;
-(IBAction)btnBookWaterproofingForInternalWetAreas_3:(id)sender;
-(IBAction)btnBookWaterproofingForInternalWetAreas_4:(id)sender;
-(IBAction)btnBookWaterproofingForInternalWetAreas_5:(id)sender;
-(IBAction)btnBookWaterproofingForInternalWetAreas_6:(id)sender;
-(IBAction)btnBookWaterproofingForInternalWetAreas_7:(id)sender;
-(IBAction)btnBookWaterproofingForInternalWetAreas_8:(id)sender;
-(IBAction)btnBookWaterproofingForInternalWetAreas_9:(id)sender;
-(IBAction)btnBookWaterproofingForInternalWetAreas_10:(id)sender;
-(IBAction)btnBookWaterproofingForInternalWetAreas_11:(id)sender;
-(IBAction)btnBookWaterproofingForInternalWetAreas_12:(id)sender;
-(IBAction)btnBookWaterproofingForInternalWetAreas_13:(id)sender;
-(IBAction)btnBookPainting_1:(id)sender;
-(IBAction)btnBookPainting_2:(id)sender;
-(IBAction)btnBookPainting_3:(id)sender;
-(IBAction)btnBookPainting_4:(id)sender;
-(IBAction)btnBookPainting_5:(id)sender;
-(IBAction)btnBookPainting_6:(id)sender;
-(IBAction)btnBookPainting_7:(id)sender;
-(IBAction)btnBookPainting_8:(id)sender;
-(IBAction)btnBookPainting_9:(id)sender;
-(IBAction)btnBookPainting_10:(id)sender;
-(IBAction)btnBookPainting_11:(id)sender;
-(IBAction)btnBookWaterproofingForExternalWall_1:(id)sender;
-(IBAction)btnBookWaterproofingForExternalWall_2:(id)sender;
-(IBAction)btnBookWaterproofingForExternalWall_3:(id)sender;
-(IBAction)btnBookWaterproofingForExternalWall_4:(id)sender;
-(IBAction)btnBookWaterproofingForExternalWall_5:(id)sender;
-(IBAction)btnBookWaterproofingForExternalWall_6:(id)sender;
-(IBAction)btnBookWaterproofingForExternalWall_7:(id)sender;
-(IBAction)btnBookWaterproofingForExternalWall_8:(id)sender;
-(IBAction)btnBookWaterproofingForExternalWall_9:(id)sender;
-(IBAction)btnBookWaterproofingForExternalWall_10:(id)sender;
-(IBAction)btnBookWaterproofingForExternalWall_11:(id)sender;
-(IBAction)btnBookTimberFlooring_1:(id)sender;
-(IBAction)btnBookTimberFlooring_2:(id)sender;
-(IBAction)btnBookTimberFlooring_3:(id)sender;
-(IBAction)btnBookTimberFlooring_4:(id)sender;
-(IBAction)btnBookTimberFlooring_5:(id)sender;
-(IBAction)btnBookTimberFlooring_6:(id)sender;
-(IBAction)btnBookTimberFlooring_7:(id)sender;
-(IBAction)btnBookTimberFlooring_8:(id)sender;
-(IBAction)btnBookTimberFlooring_9:(id)sender;
-(IBAction)btnBookTimberFlooring_10:(id)sender;
-(IBAction)btnBookTimberFlooring_11:(id)sender;
-(IBAction)btnBookTimberFlooring_12:(id)sender;
-(IBAction)btnBookTimberFlooring_13:(id)sender;
-(IBAction)btnBookAluminiumWindow_1:(id)sender;
-(IBAction)btnBookAluminiumWindow_2:(id)sender;
-(IBAction)btnBookAluminiumWindow_3:(id)sender;
-(IBAction)btnBookAluminiumWindow_4:(id)sender;
-(IBAction)btnBookAluminiumWindow_5:(id)sender;
-(IBAction)btnBookAluminiumWindow_6:(id)sender;
-(IBAction)btnBookAluminiumWindow_7:(id)sender;
-(IBAction)btnBookAluminiumWindow_8:(id)sender;
-(IBAction)btnBookAluminiumWindow_9:(id)sender;
-(IBAction)btnBookAluminiumWindow_10:(id)sender;
-(IBAction)btnBookAluminiumWindow_11:(id)sender;
-(IBAction)btnBookAluminiumWindow_12:(id)sender;
-(IBAction)btnBookAluminiumWindow_13:(id)sender;
-(IBAction)btnBookAluminiumWindow_14:(id)sender;
-(IBAction)btnBookTimberDoors_1:(id)sender;
-(IBAction)btnBookTimberDoors_2:(id)sender;
-(IBAction)btnBookTimberDoors_3:(id)sender;
-(IBAction)btnBookTimberDoors_4:(id)sender;
-(IBAction)btnBookTimberDoors_5:(id)sender;
-(IBAction)btnBookTimberDoors_6:(id)sender;
-(IBAction)btnBookTimberDoors_7:(id)sender;
-(IBAction)btnBookTimberDoors_8:(id)sender;
-(IBAction)btnBookTimberDoors_9:(id)sender;
-(IBAction)btnBookTimberDoors_10:(id)sender;
-(IBAction)btnBookTimberDoors_11:(id)sender;
-(IBAction)btnBookTimberDoors_12:(id)sender;
-(IBAction)btnBookTimberDoors_13:(id)sender;
-(IBAction)btnBookWardrobesAndKitchenCabinets_1:(id)sender;
-(IBAction)btnBookWardrobesAndKitchenCabinets_2:(id)sender;
-(IBAction)btnBookWardrobesAndKitchenCabinets_3:(id)sender;
-(IBAction)btnBookWardrobesAndKitchenCabinets_4:(id)sender;
-(IBAction)btnBookWardrobesAndKitchenCabinets_5:(id)sender;
-(IBAction)btnBookWardrobesAndKitchenCabinets_6:(id)sender;
-(IBAction)btnBookWardrobesAndKitchenCabinets_7:(id)sender;
-(IBAction)btnBookWardrobesAndKitchenCabinets_8:(id)sender;
-(IBAction)btnBookWardrobesAndKitchenCabinets_9:(id)sender;
-(IBAction)btnBookWardrobesAndKitchenCabinets_10:(id)sender;
-(IBAction)btnBookWardrobesAndKitchenCabinets_11:(id)sender;
-(IBAction)btnBookPrecastConcreteElements_1:(id)sender;
-(IBAction)btnBookPrecastConcreteElements_2:(id)sender;
-(IBAction)btnBookPrecastConcreteElements_3:(id)sender;
-(IBAction)btnBookPrecastConcreteElements_4:(id)sender;
-(IBAction)btnBookPrecastConcreteElements_5:(id)sender;
-(IBAction)btnBookPrecastConcreteElements_6:(id)sender;
-(IBAction)btnBookPrecastConcreteElements_7:(id)sender;
-(IBAction)btnBookPrecastConcreteElements_8:(id)sender;
-(IBAction)btnBookPrecastConcreteElements_9:(id)sender;
-(IBAction)btnBookPrecastConcreteElements_10:(id)sender;
-(IBAction)btnBookPrecastConcreteElements_11:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol1_1:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol1_2:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol1_3:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol1_4:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol1_5:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol1_6:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol1_7:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol1_8:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol1_9:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol1_10:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol1_11:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol1_12:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol1_13:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_1:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_2:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_3:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_4:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_5:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_6:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_7:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_8:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_9:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_10:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_11:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_12:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_13:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_14:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_15:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_16:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_17:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_18:(id)sender;
-(IBAction)btnBookDesignAndMaterialSelectionForQualityVol2_19:(id)sender;
-(IBAction)btnConquasManual6thEdition:(id)sender;
-(IBAction)btnConquasManual7thEdition:(id)sender;
-(IBAction)btnGGBSBookClicked:(id)sender;


@end
